#!/bin/bash
echo "Käynnistetään mesh-client"
sudo modprobe batman-adv
sudo killall wpa_supplicant 2>/dev/null
sudo ip link set mtu 1500 dev wlan0
sleep 1
sudo iw wlan0 set type ibss
sudo ip link set wlan0 up
sleep 2
sudo iw wlan0 ibss join mesh 2462 NOHT #HT20
sudo batctl if add wlan0
sudo ip link set bat0 up
sudo batctl gw_mode client
sudo ip link add name mesh-bridge type bridge
sudo ip link set dev eth0 master mesh-bridge
sudo ip link set dev bat0 master mesh-bridge
sudo ip link set up dev eth0
sudo ip link set up dev bat0
sudo ip link set up dev mesh-bridge
sudo ip addr add 192.168.202.2/24 broadcast 192.168.202.255 dev mesh-bridge #!! IP-tähän
sudo ip route del default 2>/dev/null
sudo ip route add default via 192.168.202.1
echo -e "Odottaa verkkoa\c"
while true; do
    if ping -c 1 -W 1 8.8.8.8 &> /dev/null
    then
        break
    fi
    echo -e ".\c"
    sleep 1
done
echo
echo Valmis
