#!/bin/bash
echo "Käynnistetään mesh-gateway"
sudo modprobe batman-adv 2>/dev/null
sudo killall wpa_supplicant
sudo sysctl -w net.ipv4.ip_forward=1 >/dev/null
sudo ip link set mtu 1500 dev wlan0
sleep 1
sudo iw wlan0 set type ibss
sudo ip link set wlan0 up
sleep 2
sudo iw wlan0 ibss join mesh 2462 NOHT #HT20 #Mhz https://en.wikipedia.org/wiki/List_of_WLAN_channels
sudo batctl if add wlan0
sudo ip link set bat0 up 
sudo batctl gw_mode server
sudo ip addr add 192.168.202.1/24 broadcast 192.168.202.255 dev bat0
#sleep 1
sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
sudo iptables -A FORWARD -i eth0 -o bat0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
sudo iptables -A FORWARD -i bat0 -o eth0 -j ACCEPT
echo "Valmis"
